<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Models\Meal;
use App\Enums\MealType;
use App\Enums\MealSource;
use App\Enums\MealStatus;
use Carbon\CarbonImmutable;
use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Meal>
 */
final class MealFactory extends Factory
{
    protected $model = Meal::class;

    public function definition(): array
    {
        return [
            // Client-generated in production; the factory stands in for the PWA.
            'uuid'       => (string) Str::uuid(),
            'status'     => MealStatus::Confirmed,
            'source'     => MealSource::Manual,
            'eaten_at'   => CarbonImmutable::instance($this->faker->dateTimeBetween('-30 days', 'now')),
            'meal_type'  => $this->faker->randomElement(MealType::cases()),
            'photo_path' => null,
            'notes'      => null,
            // local_date is generated by Postgres — never set here.
        ];
    }

    public function draft(): static
    {
        return $this->state(fn (): array => ['status' => MealStatus::Draft]);
    }

    public function proposed(): static
    {
        return $this->state(fn (): array => [
            'status' => MealStatus::Proposed,
            'source' => MealSource::Photo,
            // Load-bearing `originals/` prefix: retention prune repoints it
            // at `thumbs/`, which is how the app knows the original is gone.
            'photo_path' => 'originals/2026/08/'.$this->faker->uuid().'.jpg',
        ]);
    }

    public function photo(): static
    {
        return $this->state(fn (): array => [
            'source' => MealSource::Photo,
            // Load-bearing `originals/` prefix: retention prune repoints it
            // at `thumbs/`, which is how the app knows the original is gone.
            'photo_path' => 'originals/2026/08/'.$this->faker->uuid().'.jpg',
        ]);
    }

    public function barcode(): static
    {
        return $this->state(fn (): array => ['source' => MealSource::Barcode]);
    }

    /**
     * Normalised to UTC (see MealWriter): Eloquent writes a Carbon with no
     * offset, so a zone-aware instant handed to a timestamptz column
     * silently lands at the wrong moment.
     */
    public function eatenAt(CarbonImmutable $at): static
    {
        return $this->state(fn (): array => ['eaten_at' => $at->utc()]);
    }
}
