import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import test from 'node:test'

import { fieldFor, messageFor } from '../../resources/js/lib/validation/index.js'

/**
 * THE AGREEMENT TEST: the browser says what the server says, or says nothing.
 * Both fixtures are generated by `php artisan validation:export`; each case
 * is a value the REAL Laravel validator has already answered.
 *
 *   expected  what the browser must produce, to the letter (mirrored rules only)
 *   server    every rule judged offline — the browser may be silent where this
 *             isn't, but must never say something DIFFERENT
 *
 * A failure means a box now refuses/accepts something the server doesn't —
 * one of the two files needs regenerating, or the evaluator needs the rule.
 * tests/Feature/Validation/RulesAgreementTest.php is the PHP half.
 *
 * See docs/rationale-frontend.md § "Saying it before the round trip"
 */

const read = (path) => readFileSync(fileURLToPath(new URL(`../../${path}`, import.meta.url)), 'utf8')

const catalogue = JSON.parse(read('resources/js/lib/validation/rules.generated.json'))

const cases = read('tests/js/fixtures/validation-cases.jsonl')
  .trim()
  .split('\n')
  .map((line) => JSON.parse(line))

const describe = (subject) => `${subject.request}.${subject.field} = ${JSON.stringify(subject.data)}`

test('the fixtures cover every request and a meaningful number of values', () => {
  assert.ok(cases.length > 1500, `only ${cases.length} cases`)

  const covered = new Set(cases.map((subject) => subject.request))

  for (const request of Object.keys(catalogue.requests)) {
    const fields = Object.values(catalogue.requests[request].fields)
    const everythingIsTheServers = fields.every((field) =>
      field.rules.every((rule) => rule.server_only))

    if (everythingIsTheServers) continue

    assert.ok(covered.has(request), `${request} has no cases`)
  }
})

test('the browser produces the server sentence, word for word', () => {
  const wrong = []

  for (const subject of cases) {
    const said = messageFor(catalogue, subject.request, subject.field, subject.data)

    if (said !== subject.expected) {
      wrong.push(`${describe(subject)}\n  browser: ${said}\n  server:  ${subject.expected}`)
    }
  }

  assert.deepEqual(wrong.slice(0, 10), [], `${wrong.length} of ${cases.length} cases disagree`)
})

test('the browser never contradicts the server', () => {
  const contradictions = cases.filter((subject) => {
    const said = messageFor(catalogue, subject.request, subject.field, subject.data)

    return said !== null && said !== subject.server
  })

  assert.deepEqual(contradictions.map(describe).slice(0, 10), [])
})

test('a field only the server can judge draws no sentence at all', () => {
  const catalogued = []

  for (const [request, { fields }] of Object.entries(catalogue.requests)) {
    for (const [field, entry] of Object.entries(fields)) {
      if (!entry.rules.every((rule) => rule.server_only)) continue

      catalogued.push([request, field.replaceAll('*', '0')])
    }
  }

  // The photo upload is the case in point: a browser sentence about a file would be the wrong sentence, not a missing one.
  assert.ok(catalogued.length > 0)

  for (const [request, field] of catalogued) {
    for (const value of [null, '', 'text', 5, []]) {
      assert.equal(messageFor(catalogue, request, field, { [field]: value }), null, `${request}.${field}`)
    }
  }
})

test('an item is validated by its shape, and named by its own number', () => {
  const found = fieldFor(catalogue, 'MealRequest', 'items.7.kcal')

  assert.equal(found.index, 7)

  const said = messageFor(catalogue, 'MealRequest', 'items.7.kcal', { items: Array.from({ length: 8 }, () => ({})) })

  assert.equal(said, null, 'an empty optional box on item 7 is not an error')

  const tooBig = messageFor(
    catalogue,
    'MealRequest',
    'items.7.kcal',
    { items: [...Array.from({ length: 7 }, () => ({})), { kcal: 999999 }] },
  )

  assert.equal(
    tooBig,
    'The calories field must not be greater than 20000.',
    'the box is named the way a person says it, not by its path',
  )

  // A row whose boxes were never given a name of their own still numbers
  // itself, which is what keeps the `:index` substitution honest.
  assert.equal(
    messageFor(catalogue, 'SupplementRequest', 'nutrients.3.amount', { nutrients: [{}, {}, {}, { amount: 'text' }] }),
    'The nutrients.3.amount field must be a number.',
  )
})

/**
 * The evaluator judges the value as POSTED, not typed: the profile's boxes
 * hold "160,5" and post 160.5 (Profile.vue's `posted`) — judging the box
 * would refuse a number the save accepts, the one direction this must never be wrong in.
 */
test('a comma is not a number, which is why the caller transforms first', () => {
  const typed = messageFor(catalogue, 'ProfileRequest', 'height_cm', { height_cm: '160,5' })

  assert.match(typed, /number of centimetres/, 'the raw comma reads as text, exactly as the server reads it')

  assert.equal(messageFor(catalogue, 'ProfileRequest', 'height_cm', { height_cm: 160.5 }), null)
  assert.equal(messageFor(catalogue, 'ProfileRequest', 'height_cm', { height_cm: '160.5' }), null)
})

/**
 * WHITESPACE IS WHERE THE TWO LANGUAGES DISAGREE MOST QUIETLY — the fixtures
 * carry PHP's exotic whitespace characters, and this pins two cases they
 * cannot generate: is_numeric and filter_var disagreeing on a form feed, and
 * a form feed before a digit making Laravel's `max` throw rather than
 * answer, so there is no server sentence to generate a case from. See
 * docs/rationale-frontend.md § "Saying it before the round trip"
 */
test('whitespace is PHP\'s idea of it, not JavaScript\'s', () => {
  const empty = { items: [{ name: '\u00a0' }] }

  assert.equal(
    messageFor(catalogue, 'MealRequest', 'items.0.name', empty),
    null,
    'a non-breaking space is a character to PHP, so the name is not missing',
  )

  // ...while the characters PHP does strip still read as missing.
  for (const blank of [' ', '\t', '\n', '\r', '\v', '\0']) {
    assert.match(
      messageFor(catalogue, 'MealRequest', 'items.0.name', { items: [{ name: blank }] }),
      /field is required/,
      `PHP trims ${JSON.stringify(blank)}, so the browser must call the box empty too`,
    )
  }

  // A form feed is whitespace to is_numeric but not filter_var, so the same string is a number but not an integer.
  assert.equal(messageFor(catalogue, 'MealRequest', 'items.0.kcal', { items: [{ kcal: '\f5' }] }), null)
  assert.match(
    messageFor(catalogue, 'HealthReportRequest', 'days', { days: '\f5' }),
    /must be an integer/,
  )

  // A vertical tab is whitespace to both.
  assert.equal(messageFor(catalogue, 'HealthReportRequest', 'days', { days: '\v5' }), null)
})

test('a field nobody exported is silence, not a crash', () => {
  assert.equal(messageFor(catalogue, 'MealRequest', 'not_a_field', { not_a_field: '' }), null)
  assert.equal(messageFor(catalogue, 'NoSuchRequest', 'time', { time: '' }), null)
})
